#:schema node_modules/wrangler/config-schema.json
name = "event-api-monitoring"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
EVENTS_API_URL = "https://events.7tv.io"
