#:schema node_modules/wrangler/config-schema.json
name = "event-api-monitoring"
main = "src/index.ts"
compatibility_date = "2024-10-22"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[vars]
EVENTS_API_URL_V3_WS = "wss://events.7tv.io/v3"
EVENTS_API_URL_V3_SSE = "https://events.7tv.io/v3"
TIMEOUT = 5000 # 5 seconds
